source 'https://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'shotgun'
gem 'pry'
gem 'rake'
gem 'capybara'
gem 'launchy'
gem 'minitest'
gem 'sequel'
gem 'sqlite3'
gem 'database_cleaner'
gem 'chartkick'
gem 'haml'
gem 'prawn'
